#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

# The key lives in .env.local for `next dev`; it is gitignored.
ENV_FILE=".env.local"

banner "BenefitBridge — first deploy"

# ── 1. The spend cap, before anything is reachable ────────────────────────
stage "Anthropic — a workspace with a hard spend cap"
say "The proxy route has no login and never will, so the cap is the only real"
say "ceiling on what a stranger can spend (ADR-0012). It goes on first."
say ""
step "In the Console, create a Workspace for BenefitBridge — a cap is set per"
step "workspace, so a shared workspace would put your other keys behind it too."
step "Open that workspace's Limits page and set a monthly spend limit."
step "Pick a number you would be willing to lose outright, not a number you"
step "expect to spend — the cap's job is to bound a bad day."
open_url "https://platform.claude.com/settings/limits"
say ""
if ! confirm "Is a monthly spend limit now showing on the BenefitBridge workspace?"; then
  warn "Stop here. Nothing else in this wizard is safe to do without the cap."
  note "Re-run once it's set: scripts/first-deploy.sh"
  exit 1
fi

# ── 2. A key inside the capped workspace ──────────────────────────────────
stage "Anthropic — an API key inside that workspace"
say "The key must belong to the capped workspace. A key created in the default"
say "workspace is uncapped no matter what you set a moment ago."
open_url "https://platform.claude.com/settings/keys"
step "Create Key, and set its Workspace to the BenefitBridge workspace."
step "Copy the key — the Console shows it once."
ask_secret ANTHROPIC_API_KEY "Paste the key (hidden):"
if [[ -z "$ANTHROPIC_API_KEY" ]]; then
  warn "No key entered — nothing to deploy with."
  exit 1
fi
write_env ANTHROPIC_API_KEY "$ANTHROPIC_API_KEY"
note "That's .env.local, which is gitignored — the key does not enter the repo."

# ── 3. Link the project ───────────────────────────────────────────────────
stage "Vercel — link this directory to a project"
if ! command -v vercel >/dev/null 2>&1; then
  say "The Vercel CLI isn't installed."
  if confirm "Install it globally now (npm install -g vercel)?"; then
    npm install -g vercel
  else
    note "Install it yourself and re-run: npm install -g vercel"
    exit 1
  fi
fi
say "A browser window will open for login if you aren't signed in already."
vercel login || true
say ""
say "Linking this directory to a Vercel project (create a new one if asked):"
vercel link

# ── 4. The key, server-side only ──────────────────────────────────────────
stage "Vercel — the key as a Production environment variable"
say "Server-side only. The name must stay ANTHROPIC_API_KEY with no"
say "NEXT_PUBLIC_ prefix — that prefix is what would inline it into the"
say "browser bundle."
say ""
printf '%s' "$ANTHROPIC_API_KEY" | vercel env add ANTHROPIC_API_KEY production
say ""
if confirm "Also add it to Preview deployments?"; then
  printf '%s' "$ANTHROPIC_API_KEY" | vercel env add ANTHROPIC_API_KEY preview
  note "Preview URLs are public and unlisted, and they spend against the same cap."
fi

# ── 5. Prove the key is not in the bundle ─────────────────────────────────
stage "Verify the key never reaches the browser"
say "Building. The build searches everything the browser is served for the key,"
say "the key prefix, and the variable name, and fails if it finds any of them."
say ""
say "Vercel runs this same build, so the check gates every later deploy too —"
say "not just this one."
say ""
if ! ANTHROPIC_API_KEY="$ANTHROPIC_API_KEY" npm run build; then
  warn "The build failed, or the key reached the browser. Do NOT deploy."
  note "Read the output above, fix it, then re-run this wizard."
  exit 1
fi

# ── 6. Go public ──────────────────────────────────────────────────────────
stage "Deploy to production"
say "This puts an unauthenticated route on a public URL. It is rate limited"
say "per address, and the cap you set in stage 1 is what actually bounds it."
say ""
if ! confirm "Deploy to production now?"; then
  note "Nothing deployed. Re-run when you're ready: scripts/first-deploy.sh"
  exit 0
fi
say ""
DEPLOY_LOG=$(mktemp)
vercel deploy --prod | tee "$DEPLOY_LOG"
DEPLOY_URL=$(grep -Eo 'https://[^[:space:]]+' "$DEPLOY_LOG" | tail -n1 || true)
rm -f "$DEPLOY_LOG"
say ""
if [[ -n "$DEPLOY_URL" ]]; then
  open_url "$DEPLOY_URL"
else
  warn "Couldn't read the deployment URL from the output above — open it by hand."
  ask DEPLOY_URL "Paste the deployment URL:"
fi
say ""
step "Have a real conversation — send a message, watch the reply stream, and"
step "check the eligibility map panel renders."
step "Then refresh: the conversation should be gone (ADR-0005)."
pause "Press Enter when you've confirmed it works end to end."
say ""
step "Record the URL on the ticket so the next person can find it:"
note "  gh issue comment 14 --body 'Live at $DEPLOY_URL'"
# ──────────────────────────────────────────────────────────────────────────

finish
